### ISSUE TITLE
Implement light client sync algorithm

### ISSUE THREAD

**Issue by StoyanDrumev** [LimeChain/Fruzhin#64]
[[[Implement grandpa justifications verification algorithm]](https://spec.polkadot.network/#warp-sync)](https://spec.polkadot.network/#warp-sync) using the info coming from /sync/warp
Implement a sync query process based on this [[algorithm](https://spec.polkadot.network/#algo-light-clients-query-state)](https://spec.polkadot.network/#algo-light-clients-query-state) because it’s used by the warp sync algorithm
Persist latest finalized block information to DB

**Comment by Kirqkas** [comment]
- [x] Find snapshot with light client state, add it, read it #80 
- [x] Implement authority set change verification  #81 
- [x] Implement grandpa justification verification  #82 
- [x] Implement light client response verification algorithm and merkle proof against the Commit Root Hash from the warp sync response. See [here](https://spec.polkadot.network/sect-lightclient#algo-light-clients-query-state) for more info. #83 
- [x] Implement the light client sync algorithm based on [this](https://spec.polkadot.network/sect-lightclient#algo-warp-sync) and [this](https://spec.polkadot.network/sect-lightclient#algo-light-clients-query-state) diagrams. #84 
- [x]  #102
